author:
  name: Kevin Sheth
baseURL: http://localhost:1313
languageCode: en
menu:
  main:
    - name: Categories
      url: /categories
      weight: 1
    
    - name: Tags
      url: /tags
      weight: 2
    
    - name: About
      url: /about
      weight: 3

    - name: RSS
      weight: 4
      url: /rss

params:
  description: Exploring Theory and Practice in Reformed Theology
title: Theoretico-Practica
theme: Blogpaper

mediaTypes:
  application/rss+xml:
    suffixes: []


outputFormats:
  RSS:
    mediatype: application/rss+xml
    baseName: rss

taxonomies:
  category: categories
  tag: tags

googleAnalytics: UA-141673747-2